### ISSUE TITLE
[NFD] CPU more details discovery

### ISSUE THREAD

**Issue by ionutnechita-intel** [kubernetes-sigs/node-feature-discovery#772] opened 2022-02-08 11:21 UTC
Hi NFD Team,

I notice working correctly NFD in Rancher Cluster (RKE) with v0.10.1 version .
But i need more details/information for CPU on check architectures.

This information not exist in actual version (v0.10.1).

lscpu | grep -E "CPU family|Model|Stepping"
CPU family:                    6
Model:                           140
Model name:                 11th Gen Intel(R) Core(TM) i7-1185GRE @ 2.80GHz
Stepping:                       1

It's possible to add this options in new version?

A good day.

**Comment by marquiz** [comment] 2022-02-08 11:59
I think this is duplicate to #270

**Comment by ionutnechita-intel** [comment] 2022-02-08 12:06
It's the same issue, but the #270, is not very active.

**Comment by marquiz** [comment] 2022-02-08 12:16
You can make it more active by adding your comment there 😉. Anyways, this has been requested many times and there's even  an implementation cooking up in #700 

Closing this as a duplicate of #270.
/close

**Closed** 2022-02-08 12:16 UTC
Labels: kind/feature
